const dataBahanAjar = [
  {
    kode: "SI101",
    judul: "Pemrograman Dasar",
    kategori: "Wajib",
    upbjj: "UPBJJ Jakarta",
    lokasiRak: "R-01",
    harga: 75000,
    qty: 35,
    safety: 20,
    catatanHTML: "<i>Perlu restok bulan depan</i>",
  },
  {
    kode: "SI205",
    judul: "Basis Data",
    kategori: "Wajib",
    upbjj: "UPBJJ Surabaya",
    lokasiRak: "R-02",
    harga: 82000,
    qty: 10,
    safety: 20,
    catatanHTML: "<span style='color:red'>Stock menipis!</span>",
  },
  {
    kode: "SI301",
    judul: "Struktur Data",
    kategori: "Wajib",
    upbjj: "UPBJJ Bandung",
    lokasiRak: "R-05",
    harga: 90000,
    qty: 0,
    safety: 15,
    catatanHTML: "<i>Butuh konfirmasi dosen</i>",
  },
  {
    kode: "SI450",
    judul: "Sistem Informasi Geografis",
    kategori: "Pilihan",
    upbjj: "UPBJJ Medan",
    lokasiRak: "R-03",
    harga: 115000,
    qty: 40,
    safety: 25,
    catatanHTML: "<span style='color:green'>Stok aman</span>",
  },
  {
    kode: "SI220",
    judul: "Matematika Diskrit",
    kategori: "Wajib",
    upbjj: "UPBJJ Jakarta",
    lokasiRak: "R-04",
    harga: 70000,
    qty: 8,
    safety: 20,
    catatanHTML: "<b style='color:red'>Segera restok!</b>",
  },
  {
    kode: "SI330",
    judul: "Jaringan Komputer",
    kategori: "Wajib",
    upbjj: "UPBJJ Surabaya",
    lokasiRak: "R-06",
    harga: 92000,
    qty: 25,
    safety: 15,
    catatanHTML: "<i>Peminat tinggi semester ini</i>",
  },
  {
    kode: "SI402",
    judul: "Manajemen Proyek TI",
    kategori: "Wajib",
    upbjj: "UPBJJ Yogyakarta",
    lokasiRak: "R-07",
    harga: 88000,
    qty: 12,
    safety: 10,
    catatanHTML: "<span style='color:orange'>Cukup, awasi stok</span>",
  },
  {
    kode: "SI210",
    judul: "Algoritma Pemrograman",
    kategori: "Wajib",
    upbjj: "UPBJJ Bandung",
    lokasiRak: "R-08",
    harga: 76000,
    qty: 0,
    safety: 15,
    catatanHTML: "<b style='color:red'>STOK HABIS!</b>",
  },
  {
    kode: "SI505",
    judul: "Machine Learning",
    kategori: "Pilihan",
    upbjj: "UPBJJ Surabaya",
    lokasiRak: "R-09",
    harga: 120000,
    qty: 22,
    safety: 10,
    catatanHTML: "<i>Butuh tambahan 10 buku</i>",
  },
  {
    kode: "SI333",
    judul: "Teknologi Cloud",
    kategori: "Pilihan",
    upbjj: "UPBJJ Jakarta",
    lokasiRak: "R-10",
    harga: 98000,
    qty: 0,
    safety: 20,
    catatanHTML: "<span style='color:red'>Stock rendah!</span>",
  },
  {
    kode: "SI390",
    judul: "Interaksi Manusia dan Komputer",
    kategori: "Pilihan",
    upbjj: "UPBJJ Medan",
    lokasiRak: "R-11",
    harga: 86000,
    qty: 30,
    safety: 15,
    catatanHTML: "<span style='color:green'>Cukup</span>",
  },
  {
    kode: "SI401",
    judul: "Sistem Enterprise",
    kategori: "Wajib",
    upbjj: "UPBJJ Yogyakarta",
    lokasiRak: "R-12",
    harga: 95000,
    qty: 5,
    safety: 12,
    catatanHTML: "<b style='color:red'>Segera pesan ulang!</b>",
  },
];
